### ISSUE TITLE
Older HDL bus

### ISSUE THREAD

**Issue by janco-hdl** [roys/java-hdl-webserver#3]
Hi Roy,

I tried to use your webserver to control my older version of the HDL bus controller.

I was able to get it working (kind of) but there is a big delay between the command and the physical light change.

Do you think you will be able to help me with this problem?

Thank you very much.

Jan

**Comment by alexeyshulzhenko** [comment]
Hi, @janco-hdl, 
have you tried to check it using cURL from local network? Delay could be caused by Internet connection. I'm using 6 years old controller and it works well

**Comment by janco-hdl** [comment]
Hi Roy,

thanks for the feedback. I am running the curl cURL from the same device where the code is running. So this should be no problem.

I think there is a difference between HDL-pro protocol and HDL protocol. 

I just cant understand why there is a delay (sometimes more than 5 minutes) when I trigger the cURL request :(.

Do you have any clue where should I start with investigation?

Thank you in advance

Jan

**Comment by roys** [comment]
Hi @janco-hdl! It says I should receive notifications issues here, but clearly I don't get any. 👎  So, sorry about the lack of response.

5+ minutes delay? Wow. That sounds just crazy. What you could do is to run `tail -f hdl-bus.log`.

E.g., if this is subnet 1 and device 70 you could run something like `tail -f ~/java-hdl-webserver/releases/logs/hdl-bus.log |grep -v '1/70'` and see see the commands being sent and confirmed.

It would be interesting to see if the delay happens before you see anything in the log, or before you get some kind of response, or if it's after the device has confirmed the command.

**Comment by mhunger** [comment]
Hi Roy,

thank you for your feedback. Since I am having the older version of the controller I started to do my own research and I managed write a simple PHP code with UDP requests which is working just fine for me.

I hooked it up with Alexa (amazon echo) using OpenHAB2.

Cheers and happy coding ;)

Janco

**Comment by roys** [comment]
Ah, nice. Good work. :) Is it open source?
