### ISSUE TITLE
Can I simulate a Touch Panel?

### ISSUE THREAD

**Issue by IlPicasso** [roys/java-hdl-webserver#5]
I am wondering, I know I can trigger the lights directly, but I am wondering if I can simulate a button with hdl web server

Lets say I want to simulate touching the first button of this 
http://f.cgm.rs/HDL%20Buspro%20Setup%20Tool%202_2017-11-05_09-21-23.png

How can I do that?

**Comment by roys** [comment]
Sorry, but I haven't been getting notifications for the issues here.

So you mean like an easy way to test out the buttons directly with not having to set up anything? Unfortunately that isn't possible. But it would be very nice to have that feature. I'll surely considering adding it.

I suppose the easiest way to do this (without having to use HDL Buspro Setup Tool) would have to be to use [my Android app](https://play.google.com/store/apps/details?id=com.roysolberg.android.smarthome).
