### ISSUE TITLE
Can you help me.

### ISSUE THREAD

**Issue by lublinsky** [roys/java-hdl-webserver#6]
Web server don`t work.
I run:
curl --include --header 'Content-Type: application/json' --request POST --data '{"auth":"1N6N35453535RBK2"}' http://192.168.1.55:4567/api/actions/2

And give back answer:
curl --include --header 'Content-Type: application/json' --request POST --data '{"auth":"1N645346532"}' http://192.168.1.55:4567/api/actions/1
curl: (6) Could not resolve host: application
HTTP/1.1 500 Server Error
Date: Tue, 24 Mar 2020 18:11:36 GMT
Content-Type: text/html;charset=utf-8
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

My action:
Component -1/10
Operation -Single channel control	
Parameter 1 -3
Parameter 2 -100
Parameter 3 -0

What i have to do?

**Comment by lublinsky** [comment]
If i run on server:
curl --include --header 'Content-Type: application/json' --request POST --data '{"auth":"1N6NB3463453455BK2"}' http://192.168.1.55:4567/api/actions/2

It work ok.

HTTP/1.1 202 Accepted
Date: Tue, 24 Mar 2020 19:42:24 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

Why?
All computer in one zone in local net 192.168.1.*

**Comment by lublinsky** [comment]
CURL work in another online web server, but it don`t work on windows 10. 
I push button on ifttt.com - check now, but nothing is happening
What's the matter?[](url)

**Comment by lublinsky** [comment]
pictures https://yadi.sk/d/aAoyVqCThRlHYQ

**Comment by lublinsky** [comment]
I have done it.

**Comment by roys** [comment]
Hi @lublinsky! Sorry for being so late to the show here. You got it all working, right?

**Comment by lublinsky** [comment]
Hello, its working. Thanks.22:09, 29 апреля 2020 г., Roy Solberg <notifications@github.com>:
Hi @lublinsky! Sorry for being so late to the show here. You got it all working, right?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
